### PR TITLE
Standardize section names

### PR DESCRIPTION
**Pull request by wkolowski**
Now all sections are written like `sec_camel_case`.

### CODE REVIEW

**Review by traiansf — COMMENTED** [review]
I don't have anything against it. but I remember Karl had some ideas about camel-casing section, so I'll let him approve.

**Review by palmskog — APPROVED** [review]
This looks reasonable to me, but please add some quick motivation in the coding conventions, e.g.,
> the `sec` prefix prevents name collisions for crossreferences in coqdoc documentation

**Review by bmmoore — CHANGES_REQUESTED** [review]
It seems a bit inconsistent whether uppercase letters are used in section names that refer to CamelCase names or if the name is converted to snake_case. In many case you seem to convert names, like `Section ByzantineTraces` -> `Section sec_byzantine_traces`, but others are retained.
In `VLSM.Core.MessageDependences` there is both a `sec_full_message_dependencies` where `FullMessageDependencies` is defined, but then also a `sec_CompositeHasBeenObserved_dec` where an `Instance CompositeHasBeenObserved_dec` is defined.

Is there supposed to be a pattern here that sometimes allows CamelCase fragments?
If so it should be explained in the conventions.
If not, then as long as this PR is touching all section names we should make them all follow the "C-style" in the coding conventions.
(I think "C-style" means snake_case with uppercase only allowed for acronyms like `VLSM` or `ELMO`)

**Comment by wkolowski** [comment]
@bmmoore I think that CamelCase should be allowed to appear in section names if it refers to an identifier which is CamelCase. So I renamed `ByzantineTraces` to `sec_byzantine_traces`, because I think it didn't refer to an identifier, but I kept `sec_CompositeHasBeenReceived_dec` - this should be interpreted as a "section about `CompositeHasBeenReceived_dec`". The `FullMessageDependencies` one looks like a mistake, I will correct it.

I can add a sentence of explanation, but a full explanation would result in some kind of occult identifier hermeneutics...

**Review by wkolowski — COMMENTED** [review]
Self-review.

**Comment by bmmoore** [comment]
Looks good. I found no other places where you changed a CamelCase part of a section name that was actually matching an identifier.

**Review by bmmoore — APPROVED** [review]
Approve

**Pull request merged**
