### PR TITLE
Flatten directory structure

### PR DESCRIPTION
**Pull request by TeodorescuIoan**

### CODE REVIEW

**Comment by wkolowski** [comment]
@traiansf @palmskog @bmmoore
`theories/VLSM/Core/TraceableVLSM` contains just a single file, so maybe it shoule be flattened too?

**Comment by traiansf** [comment]
> @traiansf @palmskog @bmmoore `theories/VLSM/Core/TraceableVLSM` contains just a single file, so maybe it shoule be flattened too?

Yes, I think I've discussed with @TeodorescuIoan to move this into `Equivocation`

**Review by palmskog — COMMENTED** [review]
@TeodorescuIoan this looks like a good "flattening unit" to me, we can do further flattening/adjustments in future PRs. Maybe bring it out of draft?

**Review by palmskog — APPROVED** [review]
Looks good to me, please merge if there is no more fine-tuning required.

**Pull request merged**
