### PR TITLE
Change vlsm classes to records

### PR DESCRIPTION
**Pull request by TeodorescuIoan**

### CODE REVIEW

**Comment by TeodorescuIoan** [comment]
@palmskog  @wkolowski  This is time consuming for now (considering there are many proofs to refactor). Made this draft pull request in case there any useful changes or in case me or someone else picks this up again in the future.

**Comment by wkolowski** [comment]
Oh, now I know why I didn't refactor it earlier :) Looks like pursuing this refactoring is probably not worth it, at least for now.

**Comment by traiansf** [comment]
When I proposed it to Ioan i thought it would amount to just simple changes in the vlsm module and no changes beyond that; but we have apparently been relying on the class inference mechanism for some purposes.

**Comment by wkolowski** [comment]
I'm closing since this was implemented in #215

**Pull request closed without merging**
